### ISSUE TITLE
a piece of advice.

### ISSUE THREAD

**Issue by Hiroki-git** [postor/html5-generator#1]
强烈建议整合animate.css动画库,这样就完美了!

**Comment by postor** [comment]
谢谢建议，其实动画在打算中，还有很多细节样式参数控制也在打算中，还有打包功能，微信手Q分享功能，横屏提示，PC切换二维码等，后来就感觉实在好多要做的事额........

**Comment by postor** [comment]
针对整合animate.css，计划是先增加自定义html/css/js，增加元素默认类，把整合好的作为一个模板，然后从模板可以一键克隆。大家都可以贡献模板

**Comment by Hiroki-git** [comment]
我觉得animate.css基本上可以满足大部分动画需求。
动画这边现在的配置略显复杂,设计成这样可能反倒不方便运营层级的使用者。
拿过来,传点图片,加个动画类就成型,这个才应该是h5genrator的亮点。
另外推荐几个h5 repo,也是我今天看的
https://github.com/kele527/iSlider
https://github.com/panteng/wechat-h5-boilerplate
iscroll并非专业解决h5单页专题的方案,有时候测touch事件会失效。
可能当初lz开发的时候还没有这么多滑屏库可供选择,因此现在可以考虑优化一下。

**Comment by Hiroki-git** [comment]
我觉得animate.css基本上可以满足大部分动画需求。
动画这边现在的配置略显复杂,设计成这样可能反倒不方便运营层级的使用者。
拿过来,传点图片,加个动画类就成型,这个才应该是h5genrator的亮点。
另外推荐几个h5 repo,也是我今天看的
https://github.com/kele527/iSlider
https://github.com/panteng/wechat-h5-boilerplate
iscroll并非专业解决h5单页专题的方案,有时候测touch事件会失效。
可能当初lz开发的时候还没有这么多滑屏库可供选择,因此现在可以考虑优化一下。

**Comment by Hiroki-git** [comment]
在解决了动画问题之后,还可以在生成时预留一个空白的css供实际使用时开发自己补充样式,配置音频等等。
不得不说lz这个项目是好项目啊,可以节约很多专题的开发成本。

**Comment by postor** [comment]
我并不打算按这个想法做，网上有很多同类的编辑器，只是不开源而且大多会有自己的logo，你也可以fork一下自己实现，直接把animation.css放到配置动画的下拉里面供用户选择，工作量应该还不算太大。个人倾向于差异化一些，基于简单的配置，覆盖大部分的需求，生成精简的代码，给专业人员提供自己定制的空间。可但是呢，最近又有想法要做点别的，光有想法没时间做呢....
