### ISSUE TITLE
deprecate jade@^1.9.2 Jade has been renamed to pug, please install the latest version of pug instead of jade

### ISSUE THREAD

**Issue by albertyou2** [postor/html5-generator#3]
hi @postor nice work!
but i meet this warning when i run "cnpm i ",Does it matter?Thank you

**Comment by postor** [comment]
It should work,  so long as it is deprecate and not dropped (thermically). It is a realy old project and when I started this project pug still named jade. If you still getting problems, you can put them here

**Comment by albertyou2** [comment]
it works fine ,thanks !
